// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/JapaneseOmakaseLandingPage-hkOu-T/index.tsx": () => import("../components/mockups/templates/JapaneseOmakaseLandingPage-hkOu-T/index.tsx"),
  "./components/mockups/templates/JapaneseOmakaseLandingPage-rEIaJe/index.tsx": () => import("../components/mockups/templates/JapaneseOmakaseLandingPage-rEIaJe/index.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-923mBd/index.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-923mBd/index.tsx")
};
